services:
  springboot-green:
    container_name: coduo_springboot-app-${GREEN_SERVER_BINDING_PORT}
    image: ${DOCKER_REPO_NAME}/springboot-app:${DOCKER_IMAGE_VERSION}

    platform: linux/arm64
    ports:
      - "${GREEN_SERVER_BINDING_PORT}:${GREEN_SERVER_BINDING_PORT}"
    volumes:
      - ${SERVER_LOGS_PATH}/springboot-app:/logs
      - ${SERVER_LOGS_PATH}/springboot-app/backup:/logs/backup
    environment:
      SPRING_DATASOURCE_REPLICA_MASTER_JDBC-URL: ${MASTER_DB_URL}
      SPRING_DATASOURCE_REPLICA_MASTER_USERNAME: ${MASTER_DB_USERNAME}
      SPRING_DATASOURCE_REPLICA_MASTER_PASSWORD: ${MASTER_DB_PASSWORD}
      SPRING_DATASOURCE_REPLICA_SLAVE_JDBC-URL: ${SLAVE_DB_URL}
      SPRING_DATASOURCE_REPLICA_SLAVE_USERNAME: ${SLAVE_DB_USERNAME}
      SPRING_DATASOURCE_REPLICA_SLAVE_PASSWORD: ${SLAVE_DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL-AUTO: ${DDL_AUTO}
      OAUTH_GITHUB_CLIENT_ID: ${CLIENT_ID}
      OAUTH_GITHUB_CLIENT_SECRET: ${CLIENT_SECRET}
      OAUTH_GITHUB_REDIRECT_URI: ${CLIENT_REDIRECT_URI}
      JWT_SIGN_KEY: ${JWT_KEY}
      EC2_PREFIX: ${INSTANCE_NAME}
      SERVER_PORT: ${GREEN_SERVER_BINDING_PORT}
    restart: on-failure
    networks:
      - coduo_net

networks:
  coduo_net:
    external: true
