services:

  springboot:
    container_name: coduo_springboot-app
    image: ${DOCKER_REPO_NAME}/springboot-app:test-latest
    platform: linux/arm64
    ports:
      - ${SERVER_BINDING_PORT}
    volumes:
      - ${SERVER_LOGS_PATH}/springboot-app:/logs
      - ${SERVER_LOGS_PATH}/springboot-app/backup:/logs/backup
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL-AUTO: ${DDL_AUTO}
      OAUTH_GITHUB_CLIENT_ID: ${CLIENT_ID}
      OAUTH_GITHUB_CLIENT_SECRET: ${CLIENT_SECRET}
      OAUTH_GITHUB_REDIRECT_URI: ${CLIENT_REDIRECT_URI}
      JWT_SIGN_KEY: ${JWT_KEY}
    restart: on-failure
    networks:
      - coduo_net

networks:
  coduo_net:
    external: true
