export const QUERY_KEYS = {
  GET_REFERENCE_LINKS: 'getReferenceLinks',
  GET_PAIR_ROOM: 'getPairRoom',
  GET_PAIR_ROOM_TIMER: 'getPairRoomTimer',
  GET_PAIR_ROOM_HISTORY: 'getPairRoomHistory',
  GET_MY_PAIR_ROOMS: 'getMyPairRooms',
  GET_MEMBER_NAME: 'getMemberName',
  GET_REPOSITORIES: 'getRepositories',
  GET_BRANCHES: 'getBranches',
  GET_CATEGORIES: 'getCategories',
  GET_SIGN_IN: 'getSignIn',
  GET_SIGN_OUT: 'getSignOut',
  GET_TODOS: 'getTodos',
  GET_RETROSPECT_ANSWER: 'getRetrospectAnswer',
  GET_USER_IS_IN_PAIR_ROOM: 'getUserIsInPairRoom',
  GET_USER_RETROSPECT_EXISTS: 'getUserRetrospectExists',
  GET_MY_RETROSPECTS: 'getUserRetrospects',
};
