package site.coduo.todo.mock;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

import site.coduo.pairroom.domain.PairRoom;
import site.coduo.todo.domain.Todo;
import site.coduo.todo.service.port.TodoRepository;

public class FakeTodoRepository implements TodoRepository {

    private Long autoGeneratedId = 0L;
    public final List<Todo> data = new ArrayList<>();

    @Override
    public Todo save(final Todo todo) {
        if (todo.getId() == null || todo.getId() == 0) {
            final Todo createdTodo = new Todo(
                    ++autoGeneratedId,
                    todo.getPairRoom(),
                    todo.getContent().getContent(),
                    todo.getSort().getSort(),
                    todo.getIsChecked().isChecked()
            );
            data.add(createdTodo);
            return createdTodo;
        } else {
            data.removeIf(item -> Objects.equals(item.getId(), todo.getId()));
            data.add(todo);
            return todo;
        }
    }

    @Override
    public Optional<Todo> findTopByPairRoomOrderBySortDesc(final PairRoom pairRoom) {
        return data.stream()
                .max(Comparator.comparingInt(todo -> todo.getSort().getSort()));
    }

    @Override
    public Optional<Todo> findById(final Long id) {
        return data.stream()
                .filter(item -> Objects.equals(item.getId(), id)).findFirst();
    }

    @Override
    public void deleteById(final Long id) {
        data.removeIf(item -> Objects.equals(item.getId(), id));
    }

    @Override
    public List<Todo> findAllByPairRoomOrderBySortAsc(final PairRoom pairRoom) {
        return data.stream()
                .filter(todo -> Objects.equals(todo.getPairRoom().getId(), pairRoom.getId()))
                .sorted(Comparator.comparingInt(todo -> todo.getSort().getSort()))
                .toList();
    }
}
