spring:
  datasource:
    replica:
      master:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        maximum-pool-size: 20
      slave:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        maximum-pool-size: 20

  jpa:
    database: mysql
    hibernate:
      ddl-auto: ${DDL_AUTO}
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false

springdoc:
  swagger-ui:
    persist-authorization: true
    default-models-expand-depth: -1
    path: /api/docs

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health
      base-path: /api/actuator

server:
  tomcat:
    mbeanregistry:
      enabled: true
oauth:
  github:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    redirect-uri: ${CLIENT_REDIRECT_URI}
front:
  url: test.coduo.site

jwt:
  sign-key: ${JWT_KEY}

ec2:
  prefix: ${INSTANCE_NAME}
