CREATE TABLE IF NOT EXISTS PAIR_ROOM
(
    ID          BIGINT       NOT NULL AUTO_INCREMENT,
    PAIR1_NAME  VARCHAR(255) NOT NULL,
    PAIR2_NAME  VARCHAR(255) NOT NULL,
    ACCESS_CODE VARCHAR(50)  NOT NULL,
    CREATED_AT  TIMESTAMP    NOT NULL,
    UPDATED_AT  TIMESTAMP,

    PRIMARY KEY (ID),
    UNIQUE (ACCESS_CODE)
);
