POST https://api-test.coduo.site/api/pair-room
Content-Type: application/json

{
  "navigator": "hello",
  "driver": "world",
  "pairId": null,
  "timerDuration": 100000,
  "timerRemainingTime": 70000,
  "missionUrl": ""
}
