### 레퍼런스 링크 생성 요청
POST http://localhost:8080/reference-link
Content-Type: application/json

{
  "url": "value"
}

### 레퍼런스 링크 수정 요청
PATCH http://localhost:8080/reference-link
Content-Type: application/json

{
  "id": 1,
  "url": "change"
}
