name: Coduo Frontend CI

on:
  pull_request:
    branches: [FE/main, FE/dev]

jobs:
  unit_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.9.0"

      - name: Install dependencies
        run: yarn install

      - name: Run unit tests
        run: yarn jest

      - name: Publish storybook
        run: npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }} --storybook-config-dir=.storybook
