name: Coduo Frontend CI

on:
  pull_request:
    branches: [FE/dev, FE/test]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: print working directory
        run: pwd

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.4.1"
          cache: "yarn"

      - name: Generate yarn.lock
        run: yarn install --non-interactive
        working-directory: ./frontend

      - name: Install dependencies
        run: yarn install
        working-directory: ./frontend

      - name: Run build
        run: yarn build
        working-directory: ./frontend

      - name: Run tests
        run: yarn test
        working-directory: ./frontend

      - name: Run lint
        run: yarn lint
        working-directory: ./frontend

      - name: Run lint:css
        run: yarn lint:css
        working-directory: ./frontend

  publish-storybook:
    runs-on: ubuntu-latest
    needs: test-and-lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.4.1"
          cache: "yarn"

      - name: Generate yarn.lock
        run: yarn install --non-interactive
        working-directory: ./frontend

      - name: Install dependencies
        run: yarn install
        working-directory: ./frontend

      - name: Publish storybook
        run: npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }} --storybook-config-dir=.storybook
        working-directory: ./frontend
