name: Coduo Frontend CI

on:
  push:
    branches: [FE/dev]
  pull_request:
    branches: [FE/dev]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: print
        run: pwd

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.4.1"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Run build
        run: yarn build

      - name: Run tests
        run: yarn test

      - name: Run lint
        run: yarn lint

      - name: Run lint:css
        run: yarn lint:css

  publish-storybook:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    needs: test-and-lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.4.1"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Publish storybook
        run: npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }} --storybook-config-dir=.storybook
