name: Coduo Frontend CI

on:
  push:
    branches: [FE/test]
  pull_request:
    branches: [FE/test]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.4.1"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Run lint
        run: yarn lint:css

      - name: Run RTL tests
        run: yarn test:rtl

  publish-storybook:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    needs: test-and-lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.4.1"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Publish storybook
        run: npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }} --storybook-config-dir=.storybook
