name: Coduo Frontend Test Server CD

on:
  push:
    branches: ['FE/dev', 'FE/test']

jobs:
  build:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_ID }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Image build and push
        run: |
<<<<<<< HEAD
          docker build --platform linux/arm64 -t ${{ secrets.DOCKER_REPO_NAME }}/react-app:test-latest .
          docker push ${{ secrets.DOCKER_REPO_NAME }}/react-app:test-latest
=======
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_REPO_NAME }}/react-app:test-latest --push ./frontend
>>>>>>> ea764ff4d141a2e4e3802efa30cedb21fe1653c3

  deploy:
    environment: test
    runs-on: coduo_runner_test-server
    needs: build
    steps:
      - name: Stop and remove existing container
        run: |
          sudo docker stop coduo_react-app || true
          sudo docker rm coduo_react-app || true

      - name: Pull Docker image
        run: |
          sudo docker pull ${{ secrets.DOCKER_REPO_NAME }}/react-app:test-latest

      - name: Run Docker container
        run: |
          sudo docker run -d --network coduo_net --name coduo_react-app -p 3000:3000 ${{ secrets.DOCKER_REPO_NAME }}/react-app:test-latest
